<a href="https://colab.research.google.com/github/KIRANVVIT/CODE-FOBE-PROBLEM-STATEMENTS/blob/main/week7_assign_kiran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 7 Introduction to NumPy NumPy Array Indexing and slicing**

# **week 7, session 2, 3 May 2026, Sunday**

In [13]:
import numpy as np

1.Problem Statement: Create a 1D array of integers from 10 to 20. Access the third element of the array using its index.

Expected Output:
13

In [11]:
#Create a 1D array of integers from 10 to 20. Access the third element of the array using its index.
import numpy as np
a=np.arange(10,21)
print(f"array is {a}")
print(f"third element is {a[2]}")

array is [10 11 12 13 14 15 16 17 18 19 20]
third element is 12



2.Problem Statement: Create a 1D array of numbers from 1 to 10. Extract the first five elements.

Expected Output:

[1, 2, 3, 4, 5]




In [14]:
#Create a 1D array of numbers from 1 to 10. Extract the first five elements.
a=np.arange(1,11)
print(f"array is {a}")
print(f"first 5 elements are {a[:5]}")

array is [ 1  2  3  4  5  6  7  8  9 10]
first 5 elements are [1 2 3 4 5]



3.Problem Statement: Create a 1D array of numbers from 5 to 15. Access the last element using negative indexing.

Expected Output:
15

In [15]:
#Create a 1D array of numbers from 5 to 15. Access the last element using negative indexing.
a=np.arange(5,16)
print(f"array is {a}")
print(f"last element is {a[-1]}")

array is [ 5  6  7  8  9 10 11 12 13 14 15]
last element is 15


4.Problem Statement: Create a 1D array of even numbers from 10 to 20. Extract the last three elements using negative indexing.

Expected Output:
[16, 18, 20]

In [16]:
#Extract the last three elements using negative indexing.
a=np.arange(10,21,2)
print(f"array is {a}")
print(f"last 3 elements are {a[-3:]}")

array is [10 12 14 16 18 20]
last 3 elements are [16 18 20]



5.Problem Statement: Create a 2D array of shape (3, 3) with numbers from 1 to 9. Access the element in the second row and third column.

Expected Output:
6

In [17]:
#Create a 2D array of shape (3, 3) with numbers from 1 to 9. Access the element in the second row and third column
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"array is \n{a}")
print(f"element in 2nd row and 3rd column is {a[1,2]}")

array is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
element in 2nd row and 3rd column is 6


6.Problem Statement: Create a 2D array of shape (4, 4) with numbers from 1 to 16. Extract the second row.

Expected Output:
[5, 6, 7, 8]

In [23]:
#Create a 2D array of shape (4, 4) with numbers from 1 to 16. Extract the second row.
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(f"array is \n{a}")
print(f"second row is {a[1]}")

array is 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
second row is [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


7.Problem Statement: Create a 2D array of shape (3, 3) with numbers from 1 to 9. Extract the first column.

Expected Output:
[1, 4, 7]

In [21]:
#Create a 2D array of shape (3, 3) with numbers from 1 to 9. Extract the first column
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"array is \n{a}")
print(f"first column is {a[:,0]}")

array is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
first column is [1 4 7]


8.Problem Statement: Create a 2D array of shape (3, 3) with numbers from 1 to 9. Extract the last two rows using negative indexing.

Expected Output:

[[4, 5, 6]

 [7, 8, 9]]

In [25]:
#Create a 2D array of shape (3, 3) with numbers from 1 to 9. Extract the last two rows using negative indexing.
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"array is \n{a}")
print(f"last 2 rows are \n{a[-2:]}")

array is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
last 2 rows are 
[[4 5 6]
 [7 8 9]]


9.Problem Statement: Create a 2D array of shape (3, 4) with numbers from 1 to 12. Print its shape.

Expected Output:
(3, 4)

In [26]:
#Create a 2D array of shape (3, 4) with numbers from 1 to 12. Print its shape.
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"array is \n{a}")
print(f"shape of array is {a.shape}")

array is 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape of array is (3, 4)


10.Problem Statement: Create a 1D array of numbers from 1 to 9. Reshape it into a 3x3 array.

Expected Output:

[[1, 2, 3]

 [4, 5, 6]

 [7, 8, 9]]

In [28]:
#Create a 1D array of numbers from 1 to 9. Reshape it into a 3x3 array.
a=np.arange(1,10)
print(a)
print(a.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


11.Problem Statement: Generate a 3x3 array of random floating-point numbers between 0 and 1.

Expected Output:
A 3x3 array of random numbers (values may be different).

In [30]:
 #Generate a 3x3 array of random floating-point numbers between 0 and 1.
 import numpy as np
 a=np.random.rand(3,3)
 print(a)

[[0.49312578 0.4869985  0.36130355]
 [0.26993156 0.16436301 0.83555176]
 [0.40530246 0.85549768 0.27828909]]


12.Problem Statement: Create a 2D array of shape (3, 3) with numbers from 1 to 9. Flatten the array into a 1D array.

Expected Output:
[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
#Create a 2D array of shape (3, 3) with numbers from 1 to 9. Flatten the array into a 1D array.
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"array is \n{a}")
print(f"flattened array is {a.flatten()}")

array is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
flattened array is [1 2 3 4 5 6 7 8 9]


13.Problem Statement: Create a 2D array of shape (2, 5) with numbers from 1 to 10. Use ravel to flatten the array.

Expected Output:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [32]:
#Create a 2D array of shape (2, 5) with numbers from 1 to 10. Use ravel to flatten the array.
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"array is \n{a}")
print(f"flattened array is {a.ravel()}")

array is 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
flattened array is [ 1  2  3  4  5  6  7  8  9 10]


14.Problem Statement: Generate a 1D array of 12 random numbers between 0 and 1. Reshape it into a 3x4 array.

Expected Output:
A 3x4 array of random numbers (values may be different).

In [34]:
# Generate a 1D array of 12 random numbers between 0 and 1. Reshape it into a 3x4 array.
a=np.random.rand(12)
print(f"array is {a}")
print(f"reshaped array is \n{a.reshape(3,4)}")

array is [0.3422384  0.76595654 0.70707502 0.25010496 0.86920838 0.97780219
 0.13259452 0.71613273 0.77502663 0.95137443 0.44628606 0.0419707 ]
reshaped array is 
[[0.3422384  0.76595654 0.70707502 0.25010496]
 [0.86920838 0.97780219 0.13259452 0.71613273]
 [0.77502663 0.95137443 0.44628606 0.0419707 ]]


15.Problem Statement: Create two 1D arrays, a = [1, 2, 3] and b = [4, 5, 6]. Add these arrays element-wise.

Expected Output:
[5, 7, 9]

In [35]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(f"addition of 2 arrays is {a+b}")

addition of 2 arrays is [5 7 9]


16.Problem Statement: Create two arrays, a = [1, 2, 3] and b = [4, 5, 6]. Multiply them element-wise.

Expected Output:
[4, 10, 18]

In [36]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(f"multiplication of 2 arrays is {a*b}")

multiplication of 2 arrays is [ 4 10 18]


17.Problem Statement: Create a 1D array a = [1, 2, 3]. Multiply each element by 10.

Expected Output:
[10, 20, 30]

In [37]:
a=np.array([1,2,3])
print(f"original array is {a}")
print(f"modified array is {a*10}")

original array is [1 2 3]
modified array is [10 20 30]


18.Problem Statement: Create two arrays, a = [10, 20, 30] and b = [2, 5, 3]. Divide a by b element-wise.

Expected Output:
[5. 4. 10.]

In [38]:
a=np.array([10,20,30])
b=np.array([2,5,3])
print(f"division of 2 arrays is {a/b}")

division of 2 arrays is [ 5.  4. 10.]


19.Problem Statement: Create a 2D array [[1, 2], [3, 4]] and access the element in the second row, first column.

Expected Output:
3

In [39]:
a=np.array([[1,2],[3,4]])
print(f"array is \n{a}")
print(f"element in 2nd row and 1st column is {a[1,0]}")

array is 
[[1 2]
 [3 4]]
element in 2nd row and 1st column is 3


20.Problem Statement: Create two arrays: a = [10, 20, 30] and b = [3, 4, 5]. Compute the modulus of a divided by b element-wise.

Expected Output:
[1, 0, 0]

In [40]:
a=np.array([10,20,30])
b=np.array([3,4,5])
print(f"modulus of a divided by b is {a%b}")

modulus of a divided by b is [1 0 0]


# **week 7, session 1, 2 May 2026, Saturday**


**1.Problem Statement:**
Write a program to verify if NumPy is installed by importing it and printing its version.

**Expected Output:**
NumPy Version: 1.x.x

In [3]:
#to verify if numpu is installed and find its version
import numpy as np
print(f"numpy version is {np.__version__}")

numpy version is 2.0.2


**2.Problem Statement:**
Create a NumPy array with elements [1, 2, 3, 4, 5] and display its shape, size, and data type.

**Expected Output:**

Shape: (5,)

Size: 5

Data Type: int32 (or similar)

In [4]:
#create numpy array with 5 ele and its shape,size,datatype
import numpy as np
a=np.array([1,2,3,4,5])
print(f"array shape is {a.shape}")
print(f"array size is {a.size}")
print(f"array data type is {a.dtype}")


array shape is (5,)
array size is 5
array data type is int64


**3.Problem Statement:**
Create a 3x3 NumPy array filled with integers from 1 to 9 and display its attributes.

**Expected Output:**

Shape: (3, 3)

Size: 9

Data Type: int32

In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"array shape is {a.shape}")
print(f"array size is {a.size}")
print(f"array datatype is {a.dtype}")

array shape is (3, 3)
array size is 9
array datatype is int64


**4.Problem Statement:**
Create a 1D NumPy array with [1.1, 2.2, 3.3] and display its data type and shape.

**Expected Output:**

Shape: (3,)

Data Type: float64

In [9]:
#1D array, shape,data type
import numpy as np
a1d = np.array([1.1,2.2,3.3])
print(f"array shape is {a1d.shape}")
print(f"array datatype is {a1d.dtype}")


array shape is (3,)
array datatype is float64


**5.Problem Statement:**
What is the default data type of NumPy when creating arrays with integer or float numbers?

**Expected Output:**

Integer Default: int32

Float Default: float64

In [10]:
#default dtype of numpy when creating array with integer or float num
import numpy as np
#print(f"Integer Default: {np.}")
print(f"integer default is {np.int32}")
print(f"float default is {np.float64}")

integer default is <class 'numpy.int32'>
float default is <class 'numpy.float64'>


**6.Problem Statement:**
Create an integer array [1, 2, 3] and change its data type to float.

**Expected Output:**

[1. 2. 3.]

Data Type: float64

In [11]:
#changing int array to float type
import numpy as np
a=np.array([1,2,3])
print(f"original array is {a}")
print(f"original array datatype is {a.dtype}")
a=a.astype(np.float64)
print(f"modified array: {a}\ndatatype: {a.dtype}")

original array is [1 2 3]
original array datatype is int64
modified array: [1. 2. 3.]
datatype: float64


**7.Problem Statement:**
 Multiply two arrays [1, 2] and [3, 4] element-wise and print the result

**Expected Output:**

[3 8]

In [12]:
#multiply 2 arrays ele wise
import numpy as np
a=np.array([1,2])
b=np.array([3,4])
print(f"multiplication of 2 arrays is {a*b}")

multiplication of 2 arrays is [3 8]


**8.Problem Statement:**
Divide [10, 20, 30] by [2, 5, 10] element-wise and print the result.

**Expected Output:**

[5. 4. 3.]


In [13]:
#division of two arrays
import numpy as np
a=np.array([10,20,30])
b=np.array([2,5,10])
print(f"division of 2 arrays is {a/b}")

division of 2 arrays is [5. 4. 3.]


**9.Problem Statement:**
Create a 2x2 NumPy array with elements [[1, 2], [3, 4]].

**Expected Output:**

[[1 2]

 [3 4]]

In [15]:
#2x2 numpy array with [[1,2],[3,4]] elements
import numpy as np
a=np.array([[1,2],[3,4]])
print(f"array is \n{a}")

array is 
[[1 2]
 [3 4]]


**10.Problem Statement:**
Check the number of dimensions of a NumPy array [[1, 2], [3, 4]].

**Expected Output:**

Dimensions: 2

In [16]:
#checking dimension of numpy array
import numpy as np
a=np.array([[1,2],[3,4]])
print(f"array is \n{a}")
print(f"array dimension is {a.ndim}")


array is 
[[1 2]
 [3 4]]
array dimension is 2


**11.Problem Statement:**
Create a 1D array with values ranging from 0 to 9 using np.arange().

**Expected Output:**

[0 1 2 3 4 5 6 7 8 9]

In [17]:
#Create a 1D array with values ranging from 0 to 9 using np.arange().
import numpy as np
a=np.arange(10)
print(f"array is {a}")

array is [0 1 2 3 4 5 6 7 8 9]


**12.Problem Statement:**
Create an array of 5 evenly spaced numbers between 0 and 1 using np.linspace().

**Expected Output:**

[0.   0.25 0.5  0.75 1.  ]

In [18]:
#Create an array of 5 evenly spaced numbers between 0 and 1 using np.linspace(
import numpy as np
a=np.linspace(0,1,5)
print(f"array is \n{a}")

array is 
[0.   0.25 0.5  0.75 1.  ]


**13.Problem Statement:**
Create a 3x3 array filled with zeros using np.zeros().

**Expected Output:**

[[0. 0. 0.]

 [0. 0. 0.]

 [0. 0. 0.]]

In [2]:
#Create a 3x3 array filled with zeros using np.zeros().
import numpy as np
a=np.zeros((3,3))
print(f"array is \n {a}")

array is 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**14.Problem Statement:**
Create a 2x4 array filled with ones using np.ones().

**Expected Output:**

[[1. 1. 1. 1.]

 [1. 1. 1. 1.]]

In [3]:
import numpy as np
a=np.ones((2,4))
print(f"array is \n{a}")

array is 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**15.Problem Statement:**
Add two arrays [1, 2, 3] and [4, 5, 6].

**Expected Output**:

[5 7 9]

In [4]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(f"addition of 2 arrays is {a+b}")

addition of 2 arrays is [5 7 9]


**16.Problem Statement:**
Generate a 1D array of 5 random numbers between 0 and 1.

**Expected Output:**


[0.54 0.12 0.89 0.45 0.78]  # Example (values vary)


In [5]:
a=np.random.rand(5)
print(a)

[0.67567856 0.79660996 0.04543406 0.84040064 0.58876405]


**17.Problem Statement**:
Print the shape of a 2D array [[1, 2], [3, 4], [5, 6]]

**Expected Output**:


(3, 2)


In [6]:
a=np.array([[1,2],[3,4],[5,6]])
print(a.shape)

(3, 2)


**18.Problem Statement:**

Create a 1D NumPy array of size 5 using np.random.rand() where the array contains random decimal values between 0 and 1.

**Expected Output:**


A NumPy array of 5 random decimal values between 0 and 1, e.g.:

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]

Note: The exact output will differ because the values are generated randomly.


In [7]:
a=np.random.rand(5)
print(f"array is {a}")

array is [0.91406281 0.34547715 0.22587904 0.02891375 0.23146495]


**19.Problem Statement:**

Print the data type of elements in an array np.array([1.5, 2.0, 3.5]).


**Expected Output:**

float64

In [9]:
a=np.array([1.5,2.0,3.5])
print(f"array datatype is {a.dtype}")

array datatype is float64


**20.Problem Statement:**
Create an array of 4 evenly spaced numbers between 0 and 2 using linspace().


**Expected Output:**


[0. 0.66666667 1.33333333 2.]


In [10]:
a=np.linspace(0,2,4)
print(a)

[0.         0.66666667 1.33333333 2.        ]
