<a href="https://colab.research.google.com/github/KIRANVVIT/CODE-FOBE-PROBLEM-STATEMENTS/blob/main/week8_assign_kiran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week_8_Advanced_Numpy_Array_Operations**

# **Week 8, session 2, 10 May 2026, Sunday**

1.Problem: Split the monthly sales [100, 200, 300, 400, 500, 600] into three equal parts.

Expected Output:

[array([100, 200]), array([300, 400]), array([500, 600])]

This divides the sales array into three smaller arrays, each containing two months of sales.

In [6]:
#split slaes into 3 equal parts
import numpy as np
sales = np.array([100, 200, 300, 400, 500, 600])
split_sales = np.split(sales, 3)
print(split_sales)

[array([100, 200]), array([300, 400]), array([500, 600])]


2.Unequal Splits Using array_split()
Problem: Split [10, 20, 30, 40, 50] into 3 parts, allowing unequal splits.

Expected Output:

[array([10, 20]), array([30, 40]), array([50])]

Explanation: The array is split into 3 parts, with uneven sizes if needed.

In [7]:
#unequal split , 3 parts, using array_split()
sales = np.array([10, 20, 30, 40, 50])
split_sales = np.array_split(sales, 3)
print(split_sales)

[array([10, 20]), array([30, 40]), array([50])]


3.Splitting a 2D Sales Matrix
Problem: Split the matrix [[1, 2], [3, 4], [5, 6], [7, 8]] into two equal parts along rows.


Expected Output:

[array([[1, 2],

       [3, 4]]), array([[5, 6],

       [7, 8]])]

Explanation: The 2D array is split into two smaller arrays row-wise.

In [9]:
#splitting 2d sales matirx into 2 equal parts along rows
import numpy as np
salesmatrix2d = np.array([
    [1,2],[3,4],[5,6],[7,8]
])
split_sales = np.split(salesmatrix2d, 2, axis=0)
print(split_sales)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


4.Searching for a Product ID
Problem: Find the index of the product ID 300 in [100, 200, 300, 400, 500] using np.where.


Expected Output:

(array([2]),)

Explanation: The where() function returns the index of the matching value.

In [10]:
#find the index of product id
import numpy as np
product_ids = np.array([100, 200, 300, 400, 500])
index = np.where(product_ids == 300)
print(index)

(array([2]),)


5.Replace Low Scores
Problem: Replace all scores below 50 in [30, 60, 40, 80, 90] with 0.


Expected Output:

[ 0 60  0 80 90]

Explanation: Values below 50 are replaced with 0.



In [15]:
#replace values with 0
scores = np.array([30, 60, 40, 80, 90])
scores[scores<50] = 0
print(scores)


[ 0 60  0 80 90]


6.Problem: Find the positions/index of the value 20 in [10, 20, 30, 20, 40, 20].

Expected Output:

(array([1, 3, 5]),)

Explanation: All indices where 20 occurs are returned.

In [17]:
#find all positions where 20 occurred
values = np.array([10, 20, 30, 20, 40, 20])
positions = np.where(values == 20)
print(positions)
print(list(positions))

(array([1, 3, 5]),)
[array([1, 3, 5])]


7.Sort an Array of Prices

Problem: Sort the prices [300, 100, 400, 200] in ascending order.

Expected Output:

[100 200 300 400]


In [18]:
#array sorting in ascending order
prices = np.array([300, 100, 400, 200])
print(np.sort(prices))

[100 200 300 400]


8.Sort a 2D Array Row-Wise using axis 1

Problem: Sort each row of the 2D array [[50, 30, 20], [40, 10, 60]].


Expected Output:


[[20 30 50]

 [10 40 60]]

In [19]:
#2d array sort using axis 1
array_2d = np.array([
    [50, 30, 20],
    [40, 10, 60]
])
print(np.sort(array_2d, axis=1))

[[20 30 50]
 [10 40 60]]


9.Sort a 2D Array Column-Wise using axis 0

Problem: Sort each column of the 2D array [[50, 30], [40, 10]].


Expected Output:

[[40 10]

 [50 30]]

In [20]:
#2d array sort column wise
array_2d = np.array([
    [50, 30],
    [40, 10]
])
print(np.sort(array_2d, axis=0))

[[40 10]
 [50 30]]


10.Combine Sorting and Filtering
Problem: Sort [300, 100, 200, 400] and find all values below 250.

Expected Output:

[100 200]

In [21]:
#both sorting and filtering values
values = np.array([300, 100, 200, 400])
sorted = np.sort(values)
print(sorted[sorted<250])
print(np.sort(values[values<250]))

[100 200]
[100 200]


11.Sort Employee Salaries

Problem: Sort salaries [50000, 40000, 60000, 30000] in ascending order.


Expected Output:

[30000 40000 50000 60000]


In [22]:
#sorting sal in asce oder
salaries = np.array([50000, 40000, 60000, 30000])
print(np.sort(salaries))

[30000 40000 50000 60000]


12.Sort Names Alphabetically usimg np.sort

Problem: Sort the names ["Charlie", "Alice", "Bob"].



Expected Output:

['Alice' 'Bob' 'Charlie']

In [23]:
#sorting names
names = np.array(["Charlie", "Alice", "Bob"])
print(np.sort(names))

['Alice' 'Bob' 'Charlie']


13.Find Students Above Average Marks

Problem: Marks of students are [45, 78, 56, 89, 74, 92]. Find all students who scored above the average.



Expected Output:


Average Marks: 72.33333333333333

Above Average Marks: [78 89 74 92]

Explanation: Calculate the average using mean(). Filter values greater than the average.



In [25]:
#students above average marks
marks = np.array([45, 78, 56, 89, 74, 92])
average = np.mean(marks)
print("Average Marks:", average)
above_average = [int(x) for x in list(filter(lambda x : x > average, marks))]
print("Above Average Marks:", above_average)

Average Marks: 72.33333333333333
Above Average Marks: [78, 89, 74, 92]


14.Find and Replace Low Sales

Problem: Replace all sales below 200 in [150, 300, 100, 400] with 200.


Expected Output:


Updated Sales: [200 300 200 400]

Explanation: Use conditional indexing to replace values below the threshold.



In [27]:
#finding and replacing low sales
sales = np.array([150, 300, 100, 400])
sales[sales<200] = 200
print("Updated Sales:", sales)

Updated Sales: [200 300 200 400]


15.Find Students with Specific Grades

Problem: Student grades are [A, B, C, A, B]. Find indices of students with grade A.


Expected Output:

Indices of Students with Grade A: (array([0, 3]),)

Explanation: Use np.where() to find positions where the condition matches.

In [28]:
#indices of students with grade A
grades = np.array(["A", "B", "C", "A", "B"])
indices = np.where(grades == 'A')
print("Indices of Students with Grade A:", indices)



Indices of Students with Grade A: (array([0, 3]),)


# **week 8, session 1, 9 May 2026, Saturday**

1.Problem: You have a list of prices [100, 200, 300, 400]. Write a program to print each price one by one.

Expected Output:


100

200

300

400

In [1]:
#print list of prices one by one
prices = [100, 200, 300, 400]
for price in prices:
  print(price)


100
200
300
400



2.Problem: You have sales data for two stores:

Store 1: [150, 200, 250]

Store 2: [100, 180, 300]

Write a program to print the sales for each store.

Expected Output:

[150 200 250]

[100 180 300]

In [2]:
#print the sales of each store
store1 = [150, 200, 250]
store2 = [100, 180, 300]
print(store1)
print(store2)

[150, 200, 250]
[100, 180, 300]


3.Problem: Using the same sales data as above, print all the individual sales one by one ( one below the another).

Expected Output:

150

200

250

100

180

300


In [3]:
#printing all sales data one by one of both stores
store1 = [150, 200, 250]
store2 = [100, 180, 300]
for sale in store1:
  print(sale)
for sale in store2:
  print(sale)

150
200
250
100
180
300


4.Problem: A company records monthly sales data for 2 stores over 3 months:

Month 1: Store 1: [150, 200], Store 2: [100, 250]

Month 2: Store 1: [200, 300], Store 2: [150, 400]

Month 3: Store 1: [250, 350], Store 2: [200, 450]

Write a program to print the sales data for each month.

Expected Output:

[[150 200]

 [100 250]]

[[200 300]

 [150 400]]

[[250 350]

 [200 450]]

In [6]:
#print sales data for each month
import numpy as np
m1_store1 = [150, 200]
m1_store2 = [100, 250]
m2_store1 = [200, 300]
m2_store2 = [150, 400]
m3_store1 = [250, 350]
m3_store2 = [200, 450]
month1 = np.array([m1_store1, m1_store2])
month2 = np.array([m2_store1, m2_store2])
month3 = np.array([m3_store1, m3_store2])
print("month1")
print(month1)
print("\nmonth2")
print(month2)
print("\nmonth3")
print(month3)

month1
[[150 200]
 [100 250]]

month2
[[200 300]
 [150 400]]

month3
[[250 350]
 [200 450]]


5.Problem: Using the sales data above, print all the individual sales one by one ( one below the another).

Expected Output:

150

200

100

250

200

300

150

400

250

350

200

450


In [9]:
print(month1)
print(month2)
print(month3)
total_sales = np.concatenate([month1, month2, month3], axis=0)
print(total_sales)
for month in total_sales:
  for store in month:
    print(store)

[[150 200]
 [100 250]]
[[200 300]
 [150 400]]
[[250 350]
 [200 450]]
[[150 200]
 [100 250]
 [200 300]
 [150 400]
 [250 350]
 [200 450]]
150
200
100
250
200
300
150
400
250
350
200
450


6. Problem: Using the same 3D sales data, write a program to print all sales using nditer.

Expected Output:

150

200

100

250

200

300

150

400

250

350

200

450


In [14]:
#printing all 3d sales data using nditer
sales_3d = np.array([month1, month2, month3])
print(sales_3d)
for sale in np.nditer(sales_3d):
  print(sale)


[[[150 200]
  [100 250]]

 [[200 300]
  [150 400]]

 [[250 350]
  [200 450]]]
150
200
100
250
200
300
150
400
250
350
200
450


7.Problem: Using the same 3D sales data Calculate the total sales using the nditer() method.

Expected Output:

3000




In [15]:
#sum  of all sales using nditer
total_sales = 0
for sale in np.nditer(sales_3d):
  total_sales += sale
print(total_sales)

3000


8.Problem: using this sales = np.array([150, 250, 200, 300, 180]) Print all sales that are greater than 200.

Expected Output:

250

300

In [21]:
sales = np.array([150, 250, 200, 300, 180])
for sale in sales:
  if sale > 200:
    print(sale)
print("\nlambda fxn")
'''filtered_sales = list(filter(lambda x: x>200, sales))'''
print([int(x) for x in list(filter(lambda x: x>200, sales))])

250
300

lambda fxn
[250, 300]


9.Problem: You have product prices for Region A [100, 150, 200] and Region B [120, 140, 160]. Combine them into one array using concatination.

Expected Output:


[100 150 200 120 140 160]

In [22]:
#concatenate two arrays
reg1 = np.array([100, 150, 200])
reg2 = np.array([120, 140, 160])
print(np.concatenate([reg1, reg2]))

[100 150 200 120 140 160]


10.Problem: Sales data for January is [500, 600, 700], and February is [550, 620, 710]. Combine them horizontally to compare each product's sales using vstack.

Expected Output:

[[500 600 700]

 [550 620 710]]

In [23]:
#combining 2 arrays using vstack
jan = np.array([500, 600, 700])
feb = np.array([550, 620, 710])
print(np.vstack([jan, feb]))

[[500 600 700]
 [550 620 710]]


11.Problem: Combine sales data for three branches using vstack:

Expected Output:

Branch 1: [300, 400, 500]

Branch 2: [320, 420, 520]

Branch 3: [310, 410, 510]


In [24]:
#combining 3 branches data using vstak
branch1 = np.array([300, 400, 500])
branch2 = np.array([320, 420, 520])
branch3 = np.array([310, 410, 510])
print(np.vstack([branch1, branch2, branch3]))

[[300 400 500]
 [320 420 520]
 [310 410 510]]


12.Problem: Sales for a product are [1000, 1200, 1500], and targets are [1100, 1300, 1600]. Combine them as a 3D array for easier comparison using dstack.

Expected Output:

[[[1000 1100]

  [1200 1300]
  
  [1500 1600]]]

In [2]:
#products and targets sales are to be combined in 3d array for comparision using dstack
import numpy as np

products = np.array([1000, 1200, 1500])
targets = np.array([1100, 1300, 1600])
dstack_3d = np.dstack([products, targets])
print(dstack_3d)

[[[1000 1100]
  [1200 1300]
  [1500 1600]]]


13.Problem: Current inventory for items is [50, 60, 70]. Add new arrivals [20, 30, 40] to it using concatenate.

Expected Output:

[50 60 70 20 30 40]

In [3]:
#array concatenate
current_inventory = np.array([50, 60, 70])
new_arrivals = np.array([20, 30, 40])
print(np.concatenate([current_inventory, new_arrivals]))

[50 60 70 20 30 40]


14.Problem: Combine Student Test Scores for three subjects using vstack:

Subject A: [85, 90, 95]

Subject B: [80, 88, 92]

Subject C: [78, 85, 89]

Expected Output:

[[85 90 95]

 [80 88 92]

 [78 85 89]]


In [4]:
#combining test scores using vstack for comparision
subject_a = np.array([85, 90, 95])
subject_b = np.array([80, 88, 92])
subject_c = np.array([78, 85, 89])
print(np.vstack([subject_a, subject_b, subject_c]))

[[85 90 95]
 [80 88 92]
 [78 85 89]]


15.Problem: Math marks are [80, 85, 90] and Science marks are [70, 75, 80]. Combine them row-wise for each student using vstack.


Expected Output:


[[80 85 90]

 [70 75 80]]

In [5]:
#combining two arrays row wise using vstack
maths = np.array([80,85,90])
science = np.array([70,75,80])
print(np.vstack([maths, science]))

[[80 85 90]
 [70 75 80]]
